apiVersion: v1
kind: Service
metadata:
  name: {{ include "clair.fullname" . }}
  labels:
    {{- include "clair.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "clair.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "clair.fullname" . }}-metrics
  labels:
    {{- include "clair.labels" . | nindent 4 }}
spec:
  type: {{ .Values.introspectionService.type }}
  ports:
    - port: {{ .Values.introspectionService.port }}
      targetPort: introspection
      protocol: TCP
      name: introspection
  selector:
    {{- include "clair.selectorLabels" . | nindent 4 }}
